### ISSUE TITLE
Pull Notifications: <Hbase rowkeys>

### ISSUE THREAD

**Issue by Avinash-h** [Flipkart/connekt#169]
pull-events will have row following rowkey:
hash{appName+userID}:hash{notificationID}:hash{eventID}

Keeping following points in mind:
1. Event is pushed while creating notification.
2. qps for fetching per box: 5k.
3. write QPS targetted per box: 10k.

**Comment by kingster** [comment]
This can be now done instead via #292, which is more scalable than hbase scans
